---
title: "Pre-course self reflection (SR #1)"
format: pdf
author: "Richard Montes Lemus"
date: 2026-01-09
---

::: {.callout-note}
*For the full assignment description and grading specifications, please see the course website: <https://eds-240-data-viz.github.io/course-materials/assignments/SR1-precourse.html>*
:::

## Outline your learning goals & plan: 

  - [ ] **1. Which learning goals from the syllabus are you most excited about?** 

   I am most excited about building effective, responsible, accessible, and aesthetically-pleasing visualizations using the R programming language, and specifically {ggplot2} + ggplot2 extension packages. 
   
   I am also excited about applying a DEI lens to the process of designing data visualizations and learning the theory behind this practice. 
   

  - [ ] **2. What do you hope to get out of this class?**

   I hope to learn how to make some really beautiful visualizations that are actually clear and easy to understand. I have seen so many figures in science papers that make no sense to me so I want to make sure I avoid that. I want to learn about theories surrounding color, what makes figures intuitive to humans, and have fun designing graphs. 
   

  - [ ] **3. How do you plan on accomplishing your learning goals for this course? *Note:* be specific here! Instead of writing, “I will complete homework assignments” or “I will study,” you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday...” etc.**

   Last quarter I learned how valuable it is to stay on campus and get a majority of my work done there. Being at Bren automatically gets me into work mode and being at home gets me into rest mode. Because I have associated Bren with work, I will time block homework/review time into my google calendar for classes like these. These time blocks will mostly occur between 9am-5pm and will fill in gaps in my schedule that are not occupied with classes. During this gap, I will go to the cave and work and collaborate with other MEDS students that tend to hangout there. I'll also make an effort to store nutritious meals in the Bren kitchen so I dont have to go back home to cook and eat and can maximize my time at Bren. Once it's 5pm, I will head home. At home I'll also work on homework and other prep if needed but it should be at a less intense pace. 

## (Optional) Help me get to know you better!

  - [ ] **1. Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I've been working in industry X for Y years”)?** 

    I recently came back from Panama where I completed a year long fellowship with the Smithsonian researching tools for improving coral bleaching quantification. 

  - [ ] **2. If you have a particular career goal in mind, how does this course apply to your future career, if at all?**

    I want to be a data scientist who ideally works in AI and conservation or in the water sector. Both of these disciplines would require some data visualization experience.


  - [ ] **4. What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them?**

    I enjoy giving presentations/walk through code with the class! I think I enjoy it because I love listening to podcasts and speeches and this gives me the opportunity to apply some techniques from my favorite speakers. 


  - [ ] **6. How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why?** 

    I feel confident in R and Python. I've used both for work and undergraduate courses. Relearning these languages in MEDS really solidified them for me. The same applies for Matlab, but since we don't cover it in MEDs i'm a bit rusty.  


  - [ ] **9. What responsibilities do you have outside of school, and how do you want to balance them?**

    I work at the AIIC Center as the Graduate Projects and Analytics Coordinator for 10 hours a week. I have time blocked out for this on my calendar and I will make sure it only stays within those designated time blocks and doesn't spill over into MEDS responsibilities. 

  - [ ] **10. What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy?** 

    I like being active and loved martial arts as a kid. I will therefore, attempt to go to the gym three times a week and attend weekly jiu jitsu classes I signed up for. 

  - [ ] **11. What is a piece of media you enjoyed recently (e.g. music, book, movie, meme)?** 
  I've listened to a lot of Alanis Morissette lately. 